/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 17:32:51 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Balanca;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Balanca_ESTest extends Balanca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso(1.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso(1.2463314656494303E9, (-366.42315851));
      assertEquals((-4.566847121936618E11), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(0.0, 1342);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(337.2373875942485, 1342);
      assertEquals(452572.5741514815, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso((-337.2373875942485), (-1.0));
      assertEquals(337.2373875942485, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Balanca balanca0 = new Balanca();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem((-337.2373875942485), 1342);
      assertEquals((-452572.5741514815), double0, 0.01);
  }
}
