/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 17:35:46 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.ProdutoQuilo;
import com.example.ProdutoUnitario;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Produto_ESTest extends Produto_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo("com.example.Produto", "com.example.Produto", 0.0, 2408.4643109339);
      double double0 = produtoQuilo0.getValor();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo((String) null, (String) null, (-245.370775), (-245.370775));
      double double0 = produtoQuilo0.getValor();
      assertEquals((-245.370775), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario((String) null, (String) null, (-965.7002629));
      produtoUnitario0.getNome();
      assertEquals((-965.7002629), produtoUnitario0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario("", "", (-1651.0));
      produtoUnitario0.getNome();
      assertEquals((-1651.0), produtoUnitario0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo((String) null, (String) null, 1055.411, 1055.411);
      produtoQuilo0.getCodigo();
      assertEquals(1055.411, produtoQuilo0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo("", "", (-602.27021967903), (-856.371));
      produtoQuilo0.getCodigo();
      assertEquals((-602.27021967903), produtoQuilo0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo("com.example.ProdutoQuilo", "com.example.ProdutoQuilo", 0.0, 0.0);
      double double0 = produtoQuilo0.calcularValor((-1994.75023998133));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario((String) null, "", 1973.3516577);
      double double0 = produtoUnitario0.calcularValor(1973.3516577);
      assertEquals(3893422.8206421, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario("9vp%Q3A]^_ ", "", 1874.9592495456);
      double double0 = produtoUnitario0.calcularValor((-2383.698046855));
      assertEquals("9vp%Q3A]^_ ", produtoUnitario0.getCodigo());
      assertEquals("", produtoUnitario0.getNome());
      assertEquals((-4468027.891667165), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo((String) null, (String) null, 1055.411, 1055.411);
      double double0 = produtoQuilo0.getValor();
      assertEquals(1055.411, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario("R", "R", 462.602);
      produtoUnitario0.setValor(462.602);
      assertEquals(462.602, produtoUnitario0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario("R", "R", 462.602);
      produtoUnitario0.setNome("R");
      assertEquals(462.602, produtoUnitario0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo("com.example.ProdtoQuilo", "com.example.ProdtoQuilo", (-13.0), (-13.0));
      produtoQuilo0.setCodigo("com.example.ProdtoQuilo");
      assertEquals((-13.0), produtoQuilo0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ProdutoUnitario produtoUnitario0 = new ProdutoUnitario("R", "R", 462.602);
      produtoUnitario0.getNome();
      assertEquals(462.602, produtoUnitario0.getValor(), 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ProdutoQuilo produtoQuilo0 = new ProdutoQuilo("com.example.ProdtoQuilo", "com.example.ProdtoQuilo", (-13.0), (-13.0));
      produtoQuilo0.getCodigo();
      assertEquals((-13.0), produtoQuilo0.getValor(), 0.01);
  }
}
