/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 17:49:16 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Balanca;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Balanca_ESTest extends Balanca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso((-321.7), (-1311.610487229));
      assertEquals(421945.09374156926, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso(1174.2427878298915, (-321.7));
      assertEquals((-377753.9048448761), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(1, 1807);
      assertEquals(1807.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem((-321.7), 1);
      assertEquals((-321.7), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Balanca balanca0 = new Balanca();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(0.0, 1);
      assertEquals(0.0, double0, 0.01);
  }
}
