/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 15 16:58:49 GMT 2024
 */

package com.example;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.Balanca;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Balanca_ESTest extends Balanca_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso(0.0, 721.9);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso((-440.933998), 519.5);
      assertEquals((-229065.211961), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(0.0, 1451);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem((-1168.12362870749), 1451);
      assertEquals((-1694947.3852545682), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      double double0 = Balanca.calcularValorPorPeso((-1168.12362870749), (-1168.12362870749));
      assertEquals(1364512.811944754, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Balanca balanca0 = new Balanca();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      double double0 = Balanca.calcularValorPorItem(176.808, 1451);
      assertEquals(256548.408, double0, 0.01);
  }
}
